# Generated by Django 5.0.7 on 2024-07-31 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_Time', models.DateTimeField(auto_now=True)),
                ('Name', models.CharField(max_length=50)),
                ('Description', models.TextField()),
                ('Status', models.BooleanField(default=True)),
                ('is_modified', models.BooleanField(default=False)),
            ],
        ),
    ]
