# Generated by Django 5.0.7 on 2024-07-31 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Available_Stock', models.IntegerField(default=0)),
                ('Products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.products')),
            ],
        ),
    ]
