# Generated by Django 5.0.7 on 2024-08-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salse_customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_Time', models.DateTimeField(auto_now=True)),
                ('Transaction_code', models.CharField(max_length=20)),
                ('Customers_name', models.CharField(max_length=50)),
                ('Total_items', models.IntegerField()),
                ('Total_ammount', models.FloatField()),
                ('product_bil_data', models.TextField()),
            ],
        ),
    ]
